/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/Footer/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/Navbar/AppNavbar.vue')['default']
    HomeAboutSection: typeof import('./components/Sections/Home/HomeAboutSection.vue')['default']
    HomeClientsSection: typeof import('./components/Sections/Home/HomeClientsSection.vue')['default']
    HomeCommandSection: typeof import('./components/Sections/Home/HomeCommandSection.vue')['default']
    HomeHeadSection: typeof import('./components/Sections/Home/HomeHeadSection.vue')['default']
    HomePeculiaritiesSection: typeof import('./components/Sections/Home/HomePeculiaritiesSection.vue')['default']
    LinkButton: typeof import('./components/LinkButton.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
